development:
  clients:
    default: &default
      database: apple_weather_development
      hosts:
        - <%= ENV.fetch("MONGO_DB_URI") %>
      options:
        read:
          mode: :primary
        max_pool_size: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  clients:
    default:
      <<: *default
      database: apple_weather_test

production:
  test:
    clients:
      <<: *default
      database: apple_weather_production
