development:
  clients:
    default: &default
      uri: <%= ENV.fetch("MONGO_DB_URI") %>
      options:
        read:
          mode: :primary
        max_pool_size: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  clients:
    default:
      <<: *default
      uri: <%= ENV.fetch("MONGO_DB_URI").gsub("apple_weather_development", "apple_weather_test") %>

production:
  test:
    clients:
      <<: *default
